
import { Property, PropertyCategory } from './types';

export const CATEGORIES: PropertyCategory[] = [
  'Apartamentos',
  'Casas',
  'Airbnb',
  'Casas nuevas',
  'Casas antiguas',
  'Bodegas',
  'Apartamentos nuevos',
  'Apartamentos obra gris',
];

export const PROPERTIES: Property[] = [
  {
    id: 1,
    title: 'Moderno Apartamento en El Poblado',
    description: 'Espectacular apartamento con acabados de lujo y vista panorámica. Ideal para ejecutivos. Imagen generada por IA como representación artística.',
    price: 3500000,
    imageUrl: 'https://picsum.photos/seed/apartamento1/800/600',
    category: 'Apartamentos',
  },
  {
    id: 2,
    title: 'Casa Campestre con Piscina',
    description: 'Amplia casa rodeada de naturaleza, perfecta para familias. Cuenta con 4 habitaciones y piscina privada. Imagen generada por IA como representación artística.',
    price: 6000000,
    imageUrl: 'https://picsum.photos/seed/casa1/800/600',
    category: 'Casas',
  },
  {
    id: 3,
    title: 'Loft Acogedor para Estancias Cortas',
    description: 'Disfruta de la ciudad en este cómodo loft tipo Airbnb, totalmente equipado y con ubicación céntrica. Imagen generada por IA como representación artística.',
    price: 2800000,
    imageUrl: 'https://picsum.photos/seed/airbnb1/800/600',
    category: 'Airbnb',
  },
  {
    id: 4,
    title: 'Casa a Estrenar en Conjunto Cerrado',
    description: 'Sé el primero en habitar esta hermosa casa nueva. Diseño moderno, 3 habitaciones y seguridad 24/7. Imagen generada por IA como representación artística.',
    price: 4200000,
    imageUrl: 'https://picsum.photos/seed/casanueva1/800/600',
    category: 'Casas nuevas',
  },
  {
    id: 5,
    title: 'Casa con Encanto Histórico',
    description: 'Vive en una joya arquitectónica. Casa antigua restaurada con detalles originales y comodidades modernas. Imagen generada por IA como representación artística.',
    price: 5500000,
    imageUrl: 'https://picsum.photos/seed/casaantigua1/800/600',
    category: 'Casas antiguas',
  },
  {
    id: 6,
    title: 'Bodega Industrial de Gran Capacidad',
    description: 'Bodega de 500m² con doble altura, ideal para logística y almacenamiento. Ubicación estratégica. Imagen generada por IA como representación artística.',
    price: 8000000,
    imageUrl: 'https://picsum.photos/seed/bodega1/800/600',
    category: 'Bodegas',
  },
  {
    id: 7,
    title: 'Apartamento Nuevo en Usaquén',
    description: 'Luminoso apartamento para estrenar, con balcón y excelentes zonas comunes (gimnasio, coworking). Imagen generada por IA como representación artística.',
    price: 2800000,
    imageUrl: 'https://picsum.photos/seed/apartamentonuevo1/800/600',
    category: 'Apartamentos nuevos',
  },
  {
    id: 8,
    title: 'Apartamento en Obra Gris para Personalizar',
    description: 'Oportunidad única para diseñar el apartamento de tus sueños. Se entrega en obra gris para que lo adecues a tu gusto. Imagen generada por IA como representación artística.',
    price: 1900000,
    imageUrl: 'https://picsum.photos/seed/obragris1/800/600',
    category: 'Apartamentos obra gris',
  },
  {
    id: 9,
    title: 'Apartamento Dúplex con Terraza',
    description: 'Increíble dúplex con terraza privada y BBQ. Dos habitaciones, estudio y una vista inmejorable de la ciudad. Imagen generada por IA como representación artística.',
    price: 4800000,
    imageUrl: 'https://picsum.photos/seed/apartamento2/800/600',
    category: 'Apartamentos',
  },
  {
    id: 10,
    title: 'Casa Tradicional en La Candelaria',
    description: 'Experimenta la vida en el corazón histórico. Casa colonial con patio interior y un ambiente bohemio. Imagen generada por IA como representación artística.',
    price: 3200000,
    imageUrl: 'https://picsum.photos/seed/casaantigua2/800/600',
    category: 'Casas antiguas',
  },
   {
    id: 11,
    title: 'Apartamento Nuevo Cerca al Parque',
    description: 'Vive a pasos del parque en este moderno apartamento. Cuenta con 2 habitaciones y acabados de alta calidad. Imagen generada por IA como representación artística.',
    price: 3100000,
    imageUrl: 'https://picsum.photos/seed/apartamentonuevo2/800/600',
    category: 'Apartamentos nuevos',
  },
  {
    id: 12,
    title: 'Espaciosa Casa Familiar',
    description: 'Casa de dos niveles con jardín interior, ideal para una familia grande. Cerca a colegios y zonas comerciales. Imagen generada por IA como representación artística.',
    price: 5200000,
    imageUrl: 'https://picsum.photos/seed/casa2/800/600',
    category: 'Casas',
  },
];
